name: build windows deps

on:
  push:
    branches:
      - build_deps

jobs:
  build_dep:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'build_deps'
    - uses: ilammy/msvc-dev-cmd@v1
    - name: mkdir in deps
      run: mkdir deps/build
    - name: cmake and make deps
      working-directory: ./deps/build
      run: |
        cmake .. -G "Visual Studio 16 2019" -A x64
        msbuild /m ALL_BUILD.vcxproj
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: deps_win
        path: ./deps/build/destdir/
